/* data.js — 시드 표현 40개. 카드 관리 화면에서 수정/삭제/추가 가능. */
window.SPEAK_CATEGORIES = {
  meeting: '회의',
  opinion: '의견·동의/반대',
  request: '부탁·요청',
  schedule: '일정·약속',
  smalltalk: '스몰토크',
  followup: '이메일/통화 후속',
  reaction: '감정·반응',
  daily: '일상 필수',
  custom: '나의 표현'
};
window.SPEAK_SEED_VERSION = 1;
window.SPEAK_SEED = [
  // 회의
  { id: 'mt01', category: 'meeting', en: "Let me make sure I understand this correctly.",
    ko: "(회의에서) 제가 잘 이해했는지 확인하고 싶을 때: 제가 제대로 이해했는지 확인해볼게요",
    example: "Let me make sure I understand this correctly — you need the draft by Friday, right?",
    slot: "Let me make sure I understand ___ correctly." },
  { id: 'mt02', category: 'meeting', en: "Can I jump in here for a second?",
    ko: "(회의 중 끼어들 때) 잠깐 한마디 해도 될까요?",
    example: "Can I jump in here for a second? I think we're missing something.",
    slot: "Can I jump in here? I think ___." },
  { id: 'mt03', category: 'meeting', en: "Could you walk me through it?",
    ko: "(설명을 차근차근 듣고 싶을 때) 하나씩 설명해 주시겠어요?",
    example: "Could you walk me through the numbers on this slide?",
    slot: "Could you walk me through ___?" },
  { id: 'mt04', category: 'meeting', en: "Let's circle back to that later.",
    ko: "(지금 다룰 주제가 아닐 때) 그건 나중에 다시 얘기해요",
    example: "Good point, but let's circle back to that after we go over the budget.",
    slot: "Let's circle back to ___ later." },
  { id: 'mt05', category: 'meeting', en: "So what's the next step?",
    ko: "(회의 끝 무렵 할 일을 정할 때) 그럼 다음 단계는 뭘까요?",
    example: "So what's the next step? Who's going to follow up with the client?",
    slot: "So what's the next step for ___?" },

  // 의견·동의/반대
  { id: 'op01', category: 'opinion', en: "I see your point, but I'm not sure that'll work.",
    ko: "(부드럽게 반대할 때) 무슨 말인지는 알겠는데, 그게 잘 될지는 모르겠어요",
    example: "I see your point, but I'm not sure that'll work with our timeline.",
    slot: "I see your point, but ___." },
  { id: 'op02', category: 'opinion', en: "That makes sense.",
    ko: "(상대 말에 수긍할 때) 그거 말 되네요 / 일리 있네요",
    example: "Oh, that makes sense. I didn't think about the time difference.",
    slot: "That makes sense, especially since ___." },
  { id: 'op03', category: 'opinion', en: "I'm with you on that.",
    ko: "(전적으로 동의할 때) 그 부분은 저도 같은 생각이에요",
    example: "I'm with you on that — we need more testing before the launch.",
    slot: "I'm with you on ___." },
  { id: 'op04', category: 'opinion', en: "To be honest, I have mixed feelings about it.",
    ko: "(좋기도 하고 아니기도 할 때) 솔직히 그거에 대해선 마음이 좀 복잡해요",
    example: "To be honest, I have mixed feelings about the new policy.",
    slot: "To be honest, I have mixed feelings about ___." },
  { id: 'op05', category: 'opinion', en: "Wouldn't it be better to wait until next week?",
    ko: "(대안을 제안할 때) 다음 주까지 기다리는 게 더 낫지 않을까요?",
    example: "Wouldn't it be better to wait until next week, when everyone's back?",
    slot: "Wouldn't it be better to ___?" },

  // 부탁·요청
  { id: 'rq01', category: 'request', en: "I was wondering if you could help me with this.",
    ko: "(정중하게 부탁할 때) 혹시 이것 좀 도와주실 수 있을까 해서요",
    example: "I was wondering if you could take a quick look at my slides.",
    slot: "I was wondering if you could ___." },
  { id: 'rq02', category: 'request', en: "Would you mind sending me the file?",
    ko: "(자료를 요청할 때) 그 파일 저한테 좀 보내주실 수 있을까요?",
    example: "Would you mind sending me the file after the meeting?",
    slot: "Would you mind ___? (동사-ing: checking this, joining the call)" },
  { id: 'rq03', category: 'request', en: "Do you have a minute?",
    ko: "(동료에게 잠깐 말 걸 때) 잠깐 시간 괜찮으세요?",
    example: "Hey, do you have a minute? I have a quick question about the report.",
    slot: "Do you have a minute to ___?" },
  { id: 'rq04', category: 'request', en: "No rush, whenever you get a chance.",
    ko: "(재촉하지 않는다고 할 때) 급한 거 아니에요, 시간 날 때 해주세요",
    example: "Could you check this for me? No rush, whenever you get a chance.",
    slot: "Could you ___? No rush, whenever you get a chance." },
  { id: 'rq05', category: 'request', en: "Is there any way we could push the deadline?",
    ko: "(마감 연장을 부탁할 때) 혹시 마감을 좀 미룰 수 있는 방법이 있을까요?",
    example: "Is there any way we could push the deadline to Monday?",
    slot: "Is there any way we could ___?" },

  // 일정·약속
  { id: 'sc01', category: 'schedule', en: "Does Thursday work for you?",
    ko: "(일정을 제안할 때) 목요일 괜찮으세요?",
    example: "Does Thursday at three work for you?",
    slot: "Does ___ work for you?" },
  { id: 'sc02', category: 'schedule', en: "Something came up, so I need to reschedule.",
    ko: "(갑자기 일이 생겨 일정을 바꿀 때) 일이 좀 생겨서 일정을 다시 잡아야 할 것 같아요",
    example: "Sorry, something came up, so I need to reschedule our call.",
    slot: "Something came up, so I need to ___." },
  { id: 'sc03', category: 'schedule', en: "I'm running a few minutes late.",
    ko: "(약속에 조금 늦을 때) 몇 분 정도 늦을 것 같아요",
    example: "I'm running a few minutes late. Go ahead and start without me.",
    slot: "I'm running ___ late." },
  { id: 'sc04', category: 'schedule', en: "Let me check my schedule and get back to you.",
    ko: "(바로 답하기 어려울 때) 일정 확인해보고 다시 알려드릴게요",
    example: "Next Tuesday? Let me check my schedule and get back to you.",
    slot: "Let me check ___ and get back to you." },
  { id: 'sc05', category: 'schedule', en: "I'm tied up until three.",
    ko: "(바쁠 때) 3시까지는 일이 꽉 잡혀 있어요",
    example: "I'm tied up until three, but I'm free after that.",
    slot: "I'm tied up until ___, but ___." },

  // 스몰토크
  { id: 'sm01', category: 'smalltalk', en: "How was your weekend?",
    ko: "(월요일에 인사할 때) 주말 잘 보냈어요?",
    example: "Hey, how was your weekend? Did you do anything fun?",
    slot: "How was your ___?" },
  { id: 'sm02', category: 'smalltalk', en: "What have you been up to lately?",
    ko: "(오랜만에 만났을 때) 요즘 어떻게 지냈어요? / 요즘 뭐 하고 지내요?",
    example: "Long time no see! What have you been up to lately?",
    slot: "Lately I've been ___." },
  { id: 'sm03', category: 'smalltalk', en: "I've been swamped with work lately.",
    ko: "(근황을 말할 때) 요즘 일이 너무 많아서 정신없어요",
    example: "Sorry I haven't called. I've been swamped with work lately.",
    slot: "I've been swamped with ___ lately." },
  { id: 'sm04', category: 'smalltalk', en: "Any plans for the weekend?",
    ko: "(금요일에 가볍게 물을 때) 주말에 뭐 계획 있어요?",
    example: "Any plans for the weekend? I'm thinking of going hiking.",
    slot: "Any plans for ___?" },
  { id: 'sm05', category: 'smalltalk', en: "It's been a while! How have you been?",
    ko: "(오랜만에 만났을 때) 오랜만이에요! 어떻게 지냈어요?",
    example: "Minji! It's been a while! How have you been?",
    slot: "It's been a while since ___." },

  // 이메일/통화 후속
  { id: 'fu01', category: 'followup', en: "I'm just following up on my last email.",
    ko: "(답장이 없어 다시 연락할 때) 지난번 메일 건으로 다시 연락드려요",
    example: "Hi Tom, I'm just following up on my last email about the contract.",
    slot: "I'm just following up on ___." },
  { id: 'fu02', category: 'followup', en: "Just to recap, we agreed to launch next month.",
    ko: "(통화·회의 후 정리할 때) 정리하자면, 다음 달에 출시하기로 했죠",
    example: "Just to recap, we agreed to launch next month and review the budget on Friday.",
    slot: "Just to recap, we agreed to ___." },
  { id: 'fu03', category: 'followup', en: "Let me know if you have any questions.",
    ko: "(메일·통화를 마무리할 때) 궁금한 점 있으면 알려주세요",
    example: "I've attached the report. Let me know if you have any questions.",
    slot: "Let me know if ___." },
  { id: 'fu04', category: 'followup', en: "Sorry, you're breaking up.",
    ko: "(통화 중 소리가 끊길 때) 죄송해요, 소리가 끊겨요",
    example: "Sorry, you're breaking up. Can you hear me okay?",
    slot: "Sorry, you're breaking up. Could you ___?" },
  { id: 'fu05', category: 'followup', en: "I'll get back to you by the end of the day.",
    ko: "(답변 기한을 약속할 때) 오늘 중으로 답변 드릴게요",
    example: "Let me talk to my manager. I'll get back to you by the end of the day.",
    slot: "I'll get back to you by ___." },

  // 감정·반응
  { id: 're01', category: 'reaction', en: "That's a relief.",
    ko: "(걱정하던 일이 해결됐을 때) 다행이네요 / 한시름 놨네요",
    example: "The server is back up? Oh, that's a relief.",
    slot: "That's a relief. I was worried about ___." },
  { id: 're02', category: 'reaction', en: "I know what you mean.",
    ko: "(공감할 때) 무슨 말인지 알아요 / 저도 그래요",
    example: "I know what you mean. Mondays are always crazy for me too.",
    slot: "I know what you mean. I ___ too." },
  { id: 're03', category: 'reaction', en: "That sounds really frustrating.",
    ko: "(상대가 힘든 일을 말할 때) 정말 답답하셨겠어요",
    example: "They changed the specs again? That sounds really frustrating.",
    slot: "That sounds really ___." },
  { id: 're04', category: 'reaction', en: "No wonder you're tired.",
    ko: "(그럴 만하다고 반응할 때) 피곤할 만하네요",
    example: "You worked until midnight? No wonder you're tired.",
    slot: "No wonder ___." },
  { id: 're05', category: 'reaction', en: "I'm so glad to hear that.",
    ko: "(좋은 소식을 들었을 때) 그 말 들으니 정말 기쁘네요",
    example: "Your mom's feeling better? I'm so glad to hear that.",
    slot: "I'm so glad to hear ___." },

  // 일상 필수
  { id: 'dl01', category: 'daily', en: "Sorry, could you say that again?",
    ko: "(잘 못 알아들었을 때) 죄송한데, 다시 한번 말씀해 주시겠어요?",
    example: "Sorry, could you say that again? I didn't catch the last part.",
    slot: "Sorry, I didn't catch ___." },
  { id: 'dl02', category: 'daily', en: "What I'm trying to say is, we need more time.",
    ko: "(내 말을 다시 풀어 말할 때) 제 말은, 시간이 더 필요하다는 거예요",
    example: "What I'm trying to say is, we need more time to do this right.",
    slot: "What I'm trying to say is, ___." },
  { id: 'dl03', category: 'daily', en: "It depends on how busy I am.",
    ko: "(상황에 따라 다를 때) 그건 제가 얼마나 바쁜지에 달렸어요",
    example: "Maybe I can join. It depends on how busy I am that day.",
    slot: "It depends on ___." },
  { id: 'dl04', category: 'daily', en: "I'm not sure off the top of my head.",
    ko: "(당장 기억이 안 날 때) 지금 당장은 잘 모르겠어요",
    example: "I'm not sure off the top of my head, but I can check and let you know.",
    slot: "Off the top of my head, ___." },
  { id: 'dl05', category: 'daily', en: "How do you say that in English?",
    ko: "(영어 표현이 떠오르지 않을 때) 그걸 영어로 뭐라고 하죠?",
    example: "It's like a... how do you say that in English? A company dinner?",
    slot: "How do you say ___ in English?" }
];
